package model.entity;
// Generated Mar 16, 2018 4:43:45 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Report generated by hbm2java
 */
@Entity
@Table(name = "reports", schema = "dbo", catalog = "dailyreport")
public class Report implements java.io.Serializable {

	private Integer id;
	private Project project;
	private Task task;
	private User userByApprover;
	private User userByUserId;
	private Date timeWorked;
	private String note;
	private Date approvedAt;
	private Date createdAt;
	private Date updatedAt;

	public Report() {
	}

	public Report(Project project, Task task, User userByApprover, User userByUserId, Date timeWorked, String note,
			Date approvedAt, Date createdAt, Date updatedAt) {
		this.project = project;
		this.task = task;
		this.userByApprover = userByApprover;
		this.userByUserId = userByUserId;
		this.timeWorked = timeWorked;
		this.note = note;
		this.approvedAt = approvedAt;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "task_id")
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "approver")
	public User getUserByApprover() {
		return this.userByApprover;
	}

	public void setUserByApprover(User userByApprover) {
		this.userByApprover = userByApprover;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUserByUserId() {
		return this.userByUserId;
	}

	public void setUserByUserId(User userByUserId) {
		this.userByUserId = userByUserId;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time_worked", length = 16)
	public Date getTimeWorked() {
		return this.timeWorked;
	}

	public void setTimeWorked(Date timeWorked) {
		this.timeWorked = timeWorked;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "approved_at", length = 23)
	public Date getApprovedAt() {
		return this.approvedAt;
	}

	public void setApprovedAt(Date approvedAt) {
		this.approvedAt = approvedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 23)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
