package com.dailyreport.model;
// Generated Mar 15, 2018 9:13:02 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Report generated by hbm2java
 */
@Entity
@Table(name = "reports", schema = "dbo", catalog = "dailyreport")
public class Report implements java.io.Serializable {

	private Integer id;
	private Project project;
	private Task task;
	private User userByApprover;
	private User userByUserId;
	private Date workedAt;
	private Date workedTo;
	private String note;
	private Date createdAt;
	private Date updatedAt;
	private Integer approvalStatus;
	private Date approvedAt;

	public Report() {
	}

	public Report(Project project, Task task, User userByApprover, User userByUserId, Date workedAt, Date workedTo,
			String note, Date createdAt, Date updatedAt, Integer approvalStatus, Date approvedAt) {
		this.project = project;
		this.task = task;
		this.userByApprover = userByApprover;
		this.userByUserId = userByUserId;
		this.workedAt = workedAt;
		this.workedTo = workedTo;
		this.note = note;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.approvalStatus = approvalStatus;
		this.approvedAt = approvedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "task_id")
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "approver")
	public User getUserByApprover() {
		return this.userByApprover;
	}

	public void setUserByApprover(User userByApprover) {
		this.userByApprover = userByApprover;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUserByUserId() {
		return this.userByUserId;
	}

	public void setUserByUserId(User userByUserId) {
		this.userByUserId = userByUserId;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "worked_at", length = 16)
	public Date getWorkedAt() {
		return this.workedAt;
	}

	public void setWorkedAt(Date workedAt) {
		this.workedAt = workedAt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "worked_to", length = 16)
	public Date getWorkedTo() {
		return this.workedTo;
	}

	public void setWorkedTo(Date workedTo) {
		this.workedTo = workedTo;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 23)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "approval_status")
	public Integer getApprovalStatus() {
		return this.approvalStatus;
	}

	public void setApprovalStatus(Integer approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "approved_at", length = 23)
	public Date getApprovedAt() {
		return this.approvedAt;
	}

	public void setApprovedAt(Date approvedAt) {
		this.approvedAt = approvedAt;
	}

}
