package com.dailyreport.model;
// Generated Mar 5, 2018 3:36:32 PM by Hibernate Tools 5.2.8.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rights generated by hbm2java
 */
@Entity
@Table(name = "rights", schema = "dbo", catalog = "dailyreport")
public class Rights {

	private int id;
	private Serializable name;
	private Integer lv;
	private Date createdAt;
	private Date updateAt;
	private Set<User> users = new HashSet<User>(0);

	public Rights() {
	}

	public Rights(int id) {
		this.id = id;
	}

	public Rights(int id, Serializable name, Integer lv, Date createdAt, Date updateAt, Set<User> users) {
		this.id = id;
		this.name = name;
		this.lv = lv;
		this.createdAt = createdAt;
		this.updateAt = updateAt;
		this.users = users;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Column(name = "lv")
	public Integer getLv() {
		return this.lv;
	}

	public void setLv(Integer lv) {
		this.lv = lv;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_at", length = 23)
	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rights")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
