package com.dailyreport.model;
// Generated Mar 5, 2018 3:36:32 PM by Hibernate Tools 5.2.8.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", schema = "dbo", catalog = "dailyreport")
public class User {

	private String employeeCode;
	private Rights rights;
	private Serializable password;
	private Serializable name;
	private Date createdAt;
	private Date updatedAt;
	private Set<Report> reports = new HashSet<Report>(0);

	public User() {
	}

	public User(String employeeCode) {
		this.employeeCode = employeeCode;
	}

	public User(String employeeCode, Rights rights, Serializable password, Serializable name, Date createdAt,
			Date updatedAt, Set<Report> reports) {
		this.employeeCode = employeeCode;
		this.rights = rights;
		this.password = password;
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.reports = reports;
	}

	@Id

	@Column(name = "employee_code", unique = true, nullable = false, length = 18)
	public String getEmployeeCode() {
		return this.employeeCode;
	}

	public void setEmployeeCode(String employeeCode) {
		this.employeeCode = employeeCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rights")
	public Rights getRights() {
		return this.rights;
	}

	public void setRights(Rights rights) {
		this.rights = rights;
	}

	@Column(name = "password")
	public Serializable getPassword() {
		return this.password;
	}

	public void setPassword(Serializable password) {
		this.password = password;
	}

	@Column(name = "name")
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 23)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Report> getReports() {
		return this.reports;
	}

	public void setReports(Set<Report> reports) {
		this.reports = reports;
	}

}
