package com.dailyreport.model;
// Generated Mar 15, 2018 9:13:02 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "users", schema = "dbo", catalog = "dailyreport")
public class User implements java.io.Serializable {

	private Integer id;
	private Rights rights;
	private String employeeCode;
	private String password;
	private String name;
	private Date createdAt;
	private Date updatedAt;
	private Set<Report> reportsForApprover = new HashSet<Report>(0);
	private Set<Report> reportsForUserId = new HashSet<Report>(0);

	public User() {
	}

	public User(String employeeCode) {
		this.employeeCode = employeeCode;
	}

	public User(Rights rights, String employeeCode, String password, String name, Date createdAt, Date updatedAt,
			Set<Report> reportsForApprover, Set<Report> reportsForUserId) {
		this.rights = rights;
		this.employeeCode = employeeCode;
		this.password = password;
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.reportsForApprover = reportsForApprover;
		this.reportsForUserId = reportsForUserId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rights")
	public Rights getRights() {
		return this.rights;
	}

	public void setRights(Rights rights) {
		this.rights = rights;
	}

	@Column(name = "employee_code", nullable = false, length = 18)
	public String getEmployeeCode() {
		return this.employeeCode;
	}

	public void setEmployeeCode(String employeeCode) {
		this.employeeCode = employeeCode;
	}

	@Column(name = "password", length = 18)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 23)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByApprover")
	public Set<Report> getReportsForApprover() {
		return this.reportsForApprover;
	}

	public void setReportsForApprover(Set<Report> reportsForApprover) {
		this.reportsForApprover = reportsForApprover;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByUserId")
	public Set<Report> getReportsForUserId() {
		return this.reportsForUserId;
	}

	public void setReportsForUserId(Set<Report> reportsForUserId) {
		this.reportsForUserId = reportsForUserId;
	}

}
